import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/main-navbar";

export const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="bg-[#0e0e11]">
        <Navbar />
        <div className="mt-28 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          {children}
        </div>
      </body>
    </html>
  );
}
